# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/user/VivadoProjects/2018-3/pwm_demo/Vivado/pwm_demo_z7lite_z7020/Z7-LITE.xdc

# IP: C:/Users/user/VivadoProjects/2018-3/pwm_demo/Vivado/pwm_demo_z7lite_z7020/ip/dds_compiler_0_2/dds_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet
