set_property MARK_DEBUG true [get_nets pwm_channels_0]
set_property MARK_DEBUG true [get_nets pwm_channels_1]
set_property MARK_DEBUG true [get_nets pwm_channels_2]
set_property MARK_DEBUG true [get_nets pwm_channels_3]
set_property MARK_DEBUG true [get_nets {pwm_ref_step[0]}]
set_property MARK_DEBUG true [get_nets {pwm_ref_step[1]}]
set_property MARK_DEBUG true [get_nets {pwm_ref_step[5]}]
set_property MARK_DEBUG true [get_nets {pwm_ref_step[7]}]
set_property MARK_DEBUG true [get_nets {pwm_ref_step[9]}]
set_property MARK_DEBUG true [get_nets {sin_input[3]}]
set_property MARK_DEBUG true [get_nets {sin_input[9]}]
set_property MARK_DEBUG true [get_nets {sin_input[15]}]
set_property MARK_DEBUG true [get_nets {sin_input[1]}]
set_property MARK_DEBUG true [get_nets {sin_input[4]}]
set_property MARK_DEBUG true [get_nets {sin_input[8]}]
set_property MARK_DEBUG true [get_nets {sin_input[10]}]
set_property MARK_DEBUG true [get_nets {sin_input[11]}]
set_property MARK_DEBUG true [get_nets {sin_input[2]}]
set_property MARK_DEBUG true [get_nets {sin_input[5]}]
set_property MARK_DEBUG true [get_nets {sin_input[6]}]
set_property MARK_DEBUG true [get_nets {sin_input[14]}]
set_property MARK_DEBUG true [get_nets {sin_input[0]}]
set_property MARK_DEBUG true [get_nets {sin_input[7]}]
set_property MARK_DEBUG true [get_nets {sin_input[12]}]
set_property MARK_DEBUG true [get_nets {sin_input[13]}]
set_property MARK_DEBUG false [get_nets {left_pwm_1channel/counter_reg[11]}]
set_property MARK_DEBUG false [get_nets {left_pwm_1channel/counter_reg[10]}]
set_property MARK_DEBUG false [get_nets {left_pwm_1channel/counter[8]_i_2_n_0}]
set_property MARK_DEBUG false [get_nets {left_pwm_1channel/counter[8]_i_3_n_0}]
set_property MARK_DEBUG false [get_nets clk_mmcm_1_BUFG]
set_property MARK_DEBUG true [get_nets clk_mmcm_1]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list resolution_button_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 5 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {pwm_ref_step[0]} {pwm_ref_step[1]} {pwm_ref_step[5]} {pwm_ref_step[7]} {pwm_ref_step[9]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_mmcm_1_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 16 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {sin_input[0]} {sin_input[1]} {sin_input[2]} {sin_input[3]} {sin_input[4]} {sin_input[5]} {sin_input[6]} {sin_input[7]} {sin_input[8]} {sin_input[9]} {sin_input[10]} {sin_input[11]} {sin_input[12]} {sin_input[13]} {sin_input[14]} {sin_input[15]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list pwm_channels_0]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list pwm_channels_1]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list pwm_channels_2]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list pwm_channels_3]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list gbuf_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list clk_mmcm_1]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets gbuf_clk]
