set_property SRC_FILE_INFO {cfile:C:/Users/user/VivadoProjects/2018-3/pwm_demo/Vivado/pwm_demo_z7lite_z7020/Z7-LITE.xdc rfile:../../../Z7-LITE.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18     [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports sys_resolution_button]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports sys_pwm_channels[0]]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports sys_pwm_channels[1]]
