webtalk_init -webtalk_dir C:/Users/user/VivadoProjects/2018-3/pwm_demo/Vivado/pwm_demo_zybo_z7010/pwm_demo.sim/sim_1/behav/xsim/xsim.dir/tb_pwm_platform_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jul 10 20:43:25 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b410e80d-a597-43a9-9d1c-47335f012a73" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a6088313e18844dca2aa9a2e6c6bf5ea" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "372" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "51 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "12" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.90_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9380_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3701732658 -regid "" -xml C:/Users/user/VivadoProjects/2018-3/pwm_demo/Vivado/pwm_demo_zybo_z7010/pwm_demo.sim/sim_1/behav/xsim/xsim.dir/tb_pwm_platform_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/user/VivadoProjects/2018-3/pwm_demo/Vivado/pwm_demo_zybo_z7010/pwm_demo.sim/sim_1/behav/xsim/xsim.dir/tb_pwm_platform_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/user/VivadoProjects/2018-3/pwm_demo/Vivado/pwm_demo_zybo_z7010/pwm_demo.sim/sim_1/behav/xsim/xsim.dir/tb_pwm_platform_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
